language: node_js
node_js: node
services: mongodb
install:
  - npm install

script:
  - cd client
  - npm install
  - cd ..
  - npm ci
  - npm run client -- --silent &
  - npm run cy:run
  - npm run server -- --silent &
  - sleep 10 
  - npm test